/*Data Sistema de Facturacion
  @Author: Daniel Quiroz
  Fecha  : 01/09/2016
*/

/*Borrado de tablas*/
DELETE USUARIOS_FAC;
DELETE FACTURA;
DELETE CLIENTE;
DELETE PRODUCTOS;
DELETE DETALLE_FACTURA;
DELETE CIUDAD;
DELETE PROVINCIA;

edit USUARIOS_FAC;
/*Insercion de Usuarios*/
INSERT INTO USUARIOS_FAC (NOMBRES ,APELLIDOS,CEDULA, TELEFONO,CELULAR,CORREO,NOMBRE_USUARIO,CLAVE,ROL)
VALUES ('DANIEL','QUIROZ','40224133385','8297834604','8097100412','danielqv.120@gmail.com','dquiroz','abc123',1);
INSERT INTO USUARIOS_FAC (NOMBRES ,APELLIDOS,CEDULA, TELEFONO,CELULAR,CORREO,NOMBRE_USUARIO,CLAVE,ROL)
VALUES ('MASSIEL','QUIROZ','40224133375','8291834604','8097100812','massielqv.120@gmail.com','massielq18','abc123',0);
INSERT INTO USUARIOS_FAC (NOMBRES ,APELLIDOS,CEDULA, TELEFONO,CELULAR,CORREO,NOMBRE_USUARIO,CLAVE,ROL)
VALUES ('EDGAR','VALDEZ DIAZ','40234133375','8298834604','8097170812','edgarvd.120@gmail.com','edgarvd','abc123',0);

/*Insercion de Clientes*/
INSERT INTO CLIENTE(NOMBRES,APELLIDOS,DIRECCION,FECHA_NACIMIENTO,TELEFONO,MAIL,CATEGORIA)
VALUES('Altagracia','Valdez Suriel','Calle Emiliano Jimenez #139',TO_DATE('01/08/1971','mm/dd/yyyy'),'8095391002','altagracia@gmail.com','Cliente Premium');
INSERT INTO CLIENTE(NOMBRES,APELLIDOS,DIRECCION,FECHA_NACIMIENTO,TELEFONO,MAIL,CATEGORIA)
VALUES('Pascual','Valdez Suriel','Calle Emiliano Jimenez #141',TO_DATE('01/08/1950','mm/dd/yyyy'),'8095391004','pvaldez@gmail.com','Cliente Regular');
INSERT INTO CLIENTE(NOMBRES,APELLIDOS,DIRECCION,FECHA_NACIMIENTO,TELEFONO,MAIL,CATEGORIA)
VALUES('Juan Antonio','Valdez Suriel','Calle Emiliano Jimenez #138',TO_DATE('09/12/1974','mm/dd/yyyy'),'8095392715','juanant@gmail.com','Cliente Premium');
INSERT INTO CLIENTE(NOMBRES,APELLIDOS,DIRECCION,FECHA_NACIMIENTO,TELEFONO,MAIL,CATEGORIA)
VALUES('Carlos','Quiroz Hernandez','Calle Emiliano Jimenez #139',TO_DATE('01/08/1971','mm/dd/yyyy'),'8095391002','santoquiroz@gmail.com','Cliente Premium');
INSERT INTO CLIENTE(NOMBRES,APELLIDOS,DIRECCION,FECHA_NACIMIENTO,TELEFONO,MAIL,CATEGORIA)
VALUES('Massiel','Quiroz Valdez','Calle santiago #108',TO_DATE('05/18/1994','mm/dd/yyyy'),'8095391002','massielqv@gmail.com','Cliente Regular');
INSERT INTO CLIENTE(NOMBRES,APELLIDOS,DIRECCION,FECHA_NACIMIENTO,TELEFONO,MAIL,CATEGORIA)
VALUES('Rashell','Quiroz Valdez','Calle Emiliano Jimenez #139',TO_DATE('12/29/1997','mm/dd/yyyy'),'8095391002','rashellqv@gmail.com','Cliente Regular');


/*Insercion de Facturas*/
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,1,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,1,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,2,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,3,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,4,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,4,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,5,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,6,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,6,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,1,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,2,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,3,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,5,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,6,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,6,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,2,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,3,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,1,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,3,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,1,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,3,SYSDATE,300,700,1000);
INSERT INTO FACTURA(NUMERO_FACTURA,ID_CLIENTE,FECHA_FACTURA,ITBIS,MONTO_PARCIAL,MONTO_TOTAL)
VALUES(NUM_FACTURA.NEXTVAL,5,SYSDATE,300,700,1000);


/*Insercion de Productos*/
INSERT INTO PRODUCTOS(NOMBRE, DESCRIPCION, CODIGO, PRECIO_COMPRA, PRECIO_VENTA, NOTA, FECHA_INICIO_VENTA, FECHA_FIN_VENTA, DISPONIBLE_VENTA, FECHA_DISCONTINUIDAD, FECHA_MODIFICACION, ESTADO)
VALUES('Cafe Santo Domingo','Cafe de 2K','0123456789101',90,110,'Fabricado en Constanza RD',SYSDATE,NULL,1,NULL,SYSDATE,1);
INSERT INTO PRODUCTOS(NOMBRE, DESCRIPCION, CODIGO, PRECIO_COMPRA, PRECIO_VENTA, NOTA, FECHA_INICIO_VENTA, FECHA_FIN_VENTA, DISPONIBLE_VENTA, FECHA_DISCONTINUIDAD, FECHA_MODIFICACION, ESTADO)
VALUES('Salami Induveca','Salami Especial','0123456789102',120,150,'Fabricado en la Vega',SYSDATE,NULL,1,NULL,SYSDATE,1);
INSERT INTO PRODUCTOS(NOMBRE, DESCRIPCION, CODIGO, PRECIO_COMPRA, PRECIO_VENTA, NOTA, FECHA_INICIO_VENTA, FECHA_FIN_VENTA, DISPONIBLE_VENTA, FECHA_DISCONTINUIDAD, FECHA_MODIFICACION, ESTADO)
VALUES('Cola-Cola','Soda Coca Cola','0123456789103',20,25,'Distribuido por Coca-Cola Dominicana',SYSDATE,NULL,1,NULL,SYSDATE,1);
INSERT INTO PRODUCTOS(NOMBRE, DESCRIPCION, CODIGO, PRECIO_COMPRA, PRECIO_VENTA, NOTA, FECHA_INICIO_VENTA, FECHA_FIN_VENTA, DISPONIBLE_VENTA, FECHA_DISCONTINUIDAD, FECHA_MODIFICACION, ESTADO)
VALUES('Espagetti Princesa','Espagetti de una Libra','0123456789104',30,45,'Distribuido por Pastas Princesa',SYSDATE,NULL,1,NULL,SYSDATE,1);
INSERT INTO PRODUCTOS(NOMBRE, DESCRIPCION, CODIGO, PRECIO_COMPRA, PRECIO_VENTA, NOTA, FECHA_INICIO_VENTA, FECHA_FIN_VENTA, DISPONIBLE_VENTA, FECHA_DISCONTINUIDAD, FECHA_MODIFICACION, ESTADO)
VALUES('Espagetti Milano','Espagetti de una Libra','0123456789105',30,45,'Distribuido por Pastas Milano',SYSDATE,NULL,1,NULL,SYSDATE,1);
INSERT INTO PRODUCTOS(NOMBRE, DESCRIPCION, CODIGO, PRECIO_COMPRA, PRECIO_VENTA, NOTA, FECHA_INICIO_VENTA, FECHA_FIN_VENTA, DISPONIBLE_VENTA, FECHA_DISCONTINUIDAD, FECHA_MODIFICACION, ESTADO)
VALUES('Salsa Victornia','Salsa de Tomate','0123456789106',60,75,'Distribuido por Productos Victorina',SYSDATE,NULL,1,NULL,SYSDATE,1);
INSERT INTO PRODUCTOS(NOMBRE, DESCRIPCION, CODIGO, PRECIO_COMPRA, PRECIO_VENTA, NOTA, FECHA_INICIO_VENTA, FECHA_FIN_VENTA, DISPONIBLE_VENTA, FECHA_DISCONTINUIDAD, FECHA_MODIFICACION, ESTADO)
VALUES('Galletas Oreo','Galletas de Chocolate','0123456789107',120,160,'Distribuido por Oreo Dominicana',SYSDATE,NULL,1,NULL,SYSDATE,1);
INSERT INTO PRODUCTOS(NOMBRE, DESCRIPCION, CODIGO, PRECIO_COMPRA, PRECIO_VENTA, NOTA, FECHA_INICIO_VENTA, FECHA_FIN_VENTA, DISPONIBLE_VENTA, FECHA_DISCONTINUIDAD, FECHA_MODIFICACION, ESTADO)
VALUES('Cerveza Presidente','Cerveza Jumbo','0123456789108',90,120,'Distribuido por Cerveceria Nacional Dominicana',SYSDATE,NULL,1,NULL,SYSDATE,1);
INSERT INTO PRODUCTOS(NOMBRE, DESCRIPCION, CODIGO, PRECIO_COMPRA, PRECIO_VENTA, NOTA, FECHA_INICIO_VENTA, FECHA_FIN_VENTA, DISPONIBLE_VENTA, FECHA_DISCONTINUIDAD, FECHA_MODIFICACION, ESTADO)
VALUES('Malta Morena','Cerveza de Malta','0123456789109',18,25,'Distribuido por Cerveceria Nacional Dominicana',SYSDATE,NULL,1,NULL,SYSDATE,1);
INSERT INTO PRODUCTOS(NOMBRE, DESCRIPCION, CODIGO, PRECIO_COMPRA, PRECIO_VENTA, NOTA, FECHA_INICIO_VENTA, FECHA_FIN_VENTA, DISPONIBLE_VENTA, FECHA_DISCONTINUIDAD, FECHA_MODIFICACION, ESTADO)
VALUES('Jugo Rica','Jugo Rica de Naranga','0123456789100',120,160,'Distribuido por Rica Dominicana',SYSDATE,NULL,1,NULL,SYSDATE,1);


/*Insercion de Detalle Factura*/
INSERT INTO DETALLE_FACTURA(ID_FACTURA, ID_PRODUCTO, ID_LINEA_FACTURA, DESCRIPCION, CANTIDAD, PRECIO_UNITARIO,PRECIO_TOTAL)
VALUES(1,4,LIN_FACTURA.NEXTVAL,'Espagetti Princesa',1,45,45);
INSERT INTO DETALLE_FACTURA(ID_FACTURA, ID_PRODUCTO, ID_LINEA_FACTURA, DESCRIPCION, CANTIDAD, PRECIO_UNITARIO,PRECIO_TOTAL)
VALUES(1,5,LIN_FACTURA.NEXTVAL,'Malta Morena',10,25,250);
INSERT INTO DETALLE_FACTURA(ID_FACTURA, ID_PRODUCTO, ID_LINEA_FACTURA, DESCRIPCION, CANTIDAD, PRECIO_UNITARIO,PRECIO_TOTAL)
VALUES(1,6,LIN_FACTURA.NEXTVAL,'Salsa Victornia',2,75,150);


/*Insercion de Provincia*/
INSERT INTO PROVINCIA (NOMBRE_PROVINCIA, CAPITAL, CODIGO_PROVINCIA)
VALUES('Santo Domingo','Santo Domingo Este','30');
INSERT INTO PROVINCIA (NOMBRE_PROVINCIA, CAPITAL, CODIGO_PROVINCIA)
VALUES('Santiago','Santiago de los Caballeros','28');
INSERT INTO PROVINCIA (NOMBRE_PROVINCIA, CAPITAL, CODIGO_PROVINCIA)
VALUES('La Vega','Concepci�n de la Vega','13');
INSERT INTO PROVINCIA (NOMBRE_PROVINCIA, CAPITAL, CODIGO_PROVINCIA)
VALUES('Puerto Plata','San Felipe de Puerto Plata','20');
INSERT INTO PROVINCIA (NOMBRE_PROVINCIA, CAPITAL, CODIGO_PROVINCIA)
VALUES('Duarte','San Francisco de Macoris','5');
INSERT INTO PROVINCIA (NOMBRE_PROVINCIA, CAPITAL, CODIGO_PROVINCIA)
VALUES('Distrito Nacional','Santo Domingo de Guzman','DN');



/*Insercion de Ciudades*/
INSERT INTO CIUDAD (NOMBRE_CIUDAD, CODIGO_PROVINCIA)
VALUES('Constanza','13');
INSERT INTO CIUDAD (NOMBRE_CIUDAD, CODIGO_PROVINCIA)
VALUES('Distrito Nacional','DN');
INSERT INTO CIUDAD (NOMBRE_CIUDAD, CODIGO_PROVINCIA)
VALUES('Santiago de los Caballeros','28');
INSERT INTO CIUDAD (NOMBRE_CIUDAD, CODIGO_PROVINCIA)
VALUES('Concepcion de la Vega','13');
INSERT INTO CIUDAD (NOMBRE_CIUDAD, CODIGO_PROVINCIA)
VALUES('San Francisco de Macoris','5');
INSERT INTO CIUDAD (NOMBRE_CIUDAD, CODIGO_PROVINCIA)
VALUES('San Jose de las Matas','28');
INSERT INTO CIUDAD (NOMBRE_CIUDAD, CODIGO_PROVINCIA)
VALUES('Navarrete','28');
INSERT INTO CIUDAD (NOMBRE_CIUDAD, CODIGO_PROVINCIA)
VALUES('Santo Domingo Este','30');
INSERT INTO CIUDAD (NOMBRE_CIUDAD, CODIGO_PROVINCIA)
VALUES('Santo Domingo Norte','30');
INSERT INTO CIUDAD (NOMBRE_CIUDAD, CODIGO_PROVINCIA)
VALUES('Santo Domingo Oeste','30');


